# File: azure-pipelines.yml
trigger:
- none

variables:
  - name: version
    value: '1.0.0.1'
  - name: hydraPackageName
    value: 'org.test.package'
  - name: projectName
    value: 'application/.'

resources:
  repositories:
    - repository: scripts
      type: github
      name: healthwise/go.scripts.templates
      endpoint: DevOps

    - repository: template_scripts
      type: github
      name: holmesc1111/pipelines-dotnet-core
      endpoint: DevOps   

jobs:
  - job: setup
    steps:  
    - checkout: self
      path: "s/source"
    - task: PowerShell@2
      displayName: 'Validate version number'
      inputs:
        targetType: 'inline'
        script: |
          if (!(${{ variables.buildNversionumber }} -match '^\d{1,5}(\.\d{1,5}){2,3}$')) {Write-Error 'Bad version number supplied. Must be 3 or 4 octets using only numbers. Example: 1.0.0. 1.0.0.0' Exit 1}
