# File: azure-pipelines.yml
trigger:
- none

resources:
  repositories:
    - repository: scripts
      type: github
      name: healthwise/go.scripts.templates
      endpoint: DevOps

    - repository: template_scripts
      type: github
      name: holmesc1111/pipelines-dotnet-core
      endpoint: DevOps   

jobs:
  - job: setup
    steps:  
    - checkout: self
      path: "s/source"
    - checkout: scripts
      path: "s/scripts"
    - template: setup.yml@template_scripts
