# File: azure-pipelines.yml
trigger:
- master

resources:
  repository: template_scripts
  type: github
  name: healthwise/go.scripts.templates
  endpoint: DevOps

extends:
  template: resource-template.yml@template_scripts
