# File: azure-pipelines.yml
trigger:
- master

resources:
  repositories:
  - repository: template_scripts
    type: github
    name: holmesc1111/pipelines-dotnet-core
    endpoint: DevOps
    
extends:
  template: resource-template.yml@template_scripts    

jobs:
  - job: setup
    steps:    
    - template: setup.yml@template_scripts
