# File: azure-pipelines.yml
trigger:
- none

variables:
  - name: version
    value: '1.0.0.1'
  - name: hydraPackageName
    value: 'org.test.package'
  - name: projectName
    value: 'application/.'

resources:
  repositories:
    - repository: scripts
      type: github
      name: healthwise/go.scripts.templates
      endpoint: DevOps

    - repository: template_scripts
      type: github
      name: holmesc1111/pipelines-dotnet-core
      endpoint: DevOps   

jobs:
  - job: setup
    steps:  
    - checkout: self
      path: "s/source"
    - task: PowerShell@2
      displayName: 'Create file'
      inputs:
        targetType: inline
        script: |
          $payload = @{Version = "${{variables.version}}";ArtifactName = "${{variables.hydraPackageName}}";Content = "${{variables.projectName}}" -replace '\/\.*$',''}
          $payload | ConvertTo-Json | Set-Content ./deploy_metadata.json

    - task: PowerShell@2
      displayName: 'Output JSON file'
      inputs:
        targetType: inline
        script: |
          $metadata = Get-Content -Path './deploy_metadata.json' | ConvertFrom-Json
          Write-Output $metadata