# File: azure-pipelines.yml
trigger:
- master

resources:
  repositories:
  - repository: template_scripts
    type: github
    name: holmesc1111/pipelines-dotnet-core

extends:
  template: resource-template.yml@template_scripts
